package commandcenter.util

import java.time.ZoneId
import java.util.Locale
import scala.jdk.CollectionConverters.*
import scala.util.Try

object TimeZones {

  def get(zone: String): Option[ZoneId] = {
    val zoneNormalized = zone.toLowerCase(Locale.ENGLISH)

    all.get(zoneNormalized).orElse {
      // java.time needs these uppercase in order for it to work
      val z =
        if (zoneNormalized.startsWith("utc"))
          s"UTC${zoneNormalized.substring(3)}"
        else if (zoneNormalized.startsWith("gmt"))
          s"GMT${zoneNormalized.substring(3)}"
        else
          zoneNormalized

      Try(ZoneId.of(z)).toOption
    }
  }

  private lazy val all: Map[String, ZoneId] =
    ZoneId.getAvailableZoneIds.asScala.map { z =>
      z.toLowerCase(Locale.ENGLISH) -> ZoneId.of(z)
    }.toMap ++ aliases

  private lazy val aliases: Map[String, ZoneId] = {
    // TODO: Find a way to handle duplicate values here. For example, there are 3 `CST`. This is tricky to handle,
    // but at the very least if the user's locale is China, we should interpret it as China Standard Time.
    // The better solution might be to show all 3 values. In that case, perhaps we should add a `TimeZones.getAll`
    Map(
      "ACDT" -> "UTC+10:30",
      "ACST" -> "UTC+09:30",
//      "ACT"   -> "UTC-05",
//      "ACT"   -> "UTC+09",
      "ACT" -> "Australia/Darwin",
      "ACWST" -> "UTC+08:45",
      "ADT" -> "UTC-03",
      "AEDT" -> "UTC+11",
      "AEST" -> "UTC+10",
      "AET" -> "Australia/Sydney",
      "AFT" -> "UTC+04:30",
      "AGT" -> "America/Argentina/Buenos_Aires",
      "AKDT" -> "UTC-08",
      "AKST" -> "UTC-09",
      "ALMT" -> "UTC+06",
      "AMST" -> "UTC-03",
      "AMT" -> "UTC-04",
      "AMT" -> "UTC+04",
      "ANAT" -> "UTC+12",
      "AQTT" -> "UTC+05",
      "ART" -> "Africa/Cairo",
      "AST" -> "UTC+03",
      "AST" -> "UTC-04",
      "AWST" -> "UTC+08",
      "AZOST" -> "UTC+0",
      "AZOT" -> "UTC-01",
      "AZT" -> "UTC+04",
      "BET" -> "America/Sao_Paulo",
      "BNT" -> "UTC+08",
      "BIOT" -> "UTC+06",
      "BIT" -> "UTC-12",
      "BOT" -> "UTC-04",
      "BRST" -> "UTC-02",
      "BRT" -> "UTC-03",
      "BST" -> "UTC+06",
      "BST" -> "UTC+11",
      "BST" -> "UTC+01",
      "BTT" -> "UTC+06",
      "CAT" -> "Africa/Harare",
      "CCT" -> "UTC+06:30",
      "CDT" -> "UTC-05",
      "CDT" -> "UTC-04",
      "CEST" -> "UTC+02",
      "CET" -> "UTC+01",
      "CHADT" -> "UTC+13:45",
      "CHAST" -> "UTC+12:45",
      "CHOT" -> "UTC+08",
      "CHOST" -> "UTC+09",
      "CHST" -> "UTC+10",
      "CHUT" -> "UTC+10",
      "CIST" -> "UTC-08",
      "CKT" -> "UTC-10",
      "CLST" -> "UTC-03",
      "CLT" -> "UTC-04",
      "COST" -> "UTC-04",
      "COT" -> "UTC-05",
//      "CST"   -> "UTC-06",
//      "CST"   -> "UTC+08",
//      "CST"   -> "UTC-05",
      "CST" -> "Asia/Shanghai",
      "CT" -> "UTC-06",
      "CVT" -> "UTC-01",
      "CWST" -> "UTC+08:45",
      "CXT" -> "UTC+07",
      "DAVT" -> "UTC+07",
      "DDUT" -> "UTC+10",
      "DFT" -> "UTC+01",
      "EASST" -> "UTC-05",
      "EAST" -> "UTC-06",
      "EAT" -> "UTC+03",
//      "ECT"   -> "UTC-04",
//      "ECT"   -> "UTC-05",
      "ECT" -> "Europe/Paris",
      "EDT" -> "UTC-04",
      "EEST" -> "UTC+03",
      "EET" -> "UTC+02",
      "EGST" -> "UTC+0",
      "EGT" -> "UTC-01",
      "EST" -> "UTC-05",
      "FET" -> "UTC+03",
      "FJT" -> "UTC+12",
      "FKST" -> "UTC-03",
      "FKT" -> "UTC-04",
      "FNT" -> "UTC-02",
      "GALT" -> "UTC-06",
      "GAMT" -> "UTC-09",
      "GET" -> "UTC+04",
      "GFT" -> "UTC-03",
      "GILT" -> "UTC+12",
      "GIT" -> "UTC-09",
      "GMT" -> "UTC+0",
      "GST" -> "UTC-02",
      "GST" -> "UTC+04",
      "GYT" -> "UTC-04",
      "HDT" -> "UTC-09",
      "HAEC" -> "UTC+02",
      "HST" -> "UTC-10",
      "HKT" -> "UTC+08",
      "HMT" -> "UTC+05",
      "HOVST" -> "UTC+08",
      "HOVT" -> "UTC+07",
      "ICT" -> "UTC+07",
      "IDLW" -> "UTC-12",
      "IDT" -> "UTC+03",
      "IOT" -> "UTC+03",
      "IRDT" -> "UTC+04:30",
      "IRKT" -> "UTC+08",
      "IRST" -> "UTC+03:30",
//      "IST"   -> "UTC+05:30",
//      "IST"   -> "UTC+01",
//      "IST"   -> "UTC+02",
      "IST" -> "Asia/Kolkata",
      "JST" -> "Asia/Tokyo",
      "KALT" -> "UTC+02",
      "KGT" -> "UTC+06",
      "KOST" -> "UTC+11",
      "KRAT" -> "UTC+07",
      "KST" -> "UTC+09",
      "LHST" -> "UTC+10:30",
      "LHST" -> "UTC+11",
      "LINT" -> "UTC+14",
      "MAGT" -> "UTC+12",
      "MART" -> "UTC-09:30",
      "MAWT" -> "UTC+05",
      "MDT" -> "UTC-06",
      "MET" -> "UTC+01",
      "MEST" -> "UTC+02",
      "MHT" -> "UTC+12",
      "MIST" -> "UTC+11",
      "MIT" -> "Pacific/Apia",
      "MMT" -> "UTC+06:30",
      "MSK" -> "UTC+03",
      "MST" -> "UTC+08",
      "MST" -> "UTC-07",
      "MUT" -> "UTC+04",
      "MVT" -> "UTC+05",
      "MYT" -> "UTC+08",
      "NCT" -> "UTC+11",
      "NDT" -> "UTC-02:30",
      "NFT" -> "UTC+11",
      "NOVT" -> "UTC+07",
      "NET" -> "Asia/Yerevan",
      "NPT" -> "UTC+05:45",
      "NST" -> "Pacific/Auckland",
      "NT" -> "UTC-03:30",
      "NUT" -> "UTC-11",
      "NZDT" -> "UTC+13",
      "NZST" -> "UTC+12",
      "OMST" -> "UTC+06",
      "ORAT" -> "UTC+05",
      "PDT" -> "UTC-07",
      "PET" -> "UTC-05",
      "PETT" -> "UTC+12",
      "PGT" -> "UTC+10",
      "PHOT" -> "UTC+13",
      "PHT" -> "UTC+08",
      "PKT" -> "UTC+05",
      "PMDT" -> "UTC-02",
      "PMST" -> "UTC-03",
      "PNT" -> "America/Phoenix",
      "PONT" -> "UTC+11",
//      "PST"   -> "UTC-08",
//      "PST"   -> "UTC+08",
      "PRT" -> "America/Puerto_Rico",
      "PST" -> "America/Los_Angeles",
      "PWT" -> "UTC+09",
      "PYST" -> "UTC-03",
      "PYT" -> "UTC-04",
      "RET" -> "UTC+04",
      "ROTT" -> "UTC-03",
      "SAKT" -> "UTC+11",
      "SAMT" -> "UTC+04",
      "SAST" -> "UTC+02",
      "SBT" -> "UTC+11",
      "SCT" -> "UTC+04",
      "SDT" -> "UTC-10",
      "SGT" -> "UTC+08",
      "SLST" -> "UTC+05:30",
      "SRET" -> "UTC+11",
      "SRT" -> "UTC-03",
      "SST" -> "UTC-11",
      "SST" -> "UTC+08",
      "SYOT" -> "UTC+03",
      "TAHT" -> "UTC-10",
      "THA" -> "UTC+07",
      "TFT" -> "UTC+05",
      "TJT" -> "UTC+05",
      "TKT" -> "UTC+13",
      "TLT" -> "UTC+09",
      "TMT" -> "UTC+05",
      "TRT" -> "UTC+03",
      "TOT" -> "UTC+13",
      "TVT" -> "UTC+12",
      "ULAST" -> "UTC+09",
      "ULAT" -> "UTC+08",
      "UTC" -> "UTC+0",
      "UYST" -> "UTC-02",
      "UYT" -> "UTC-03",
      "UZT" -> "UTC+05",
      "VET" -> "UTC-04",
      "VLAT" -> "UTC+10",
      "VOLT" -> "UTC+04",
      "VOST" -> "UTC+06",
      "VST" -> "Asia/Ho_Chi_Minh",
      "VUT" -> "UTC+11",
      "WAKT" -> "UTC+12",
      "WAST" -> "UTC+02",
      "WAT" -> "UTC+01",
      "WEST" -> "UTC+01",
      "WET" -> "UTC+0",
      "WIB" -> "UTC+07",
      "WIT" -> "UTC+09",
      "WITA" -> "UTC+08",
      "WGST" -> "UTC-02",
      "WGT" -> "UTC-03",
      "WST" -> "UTC+08",
      "YAKT" -> "UTC+09",
      "YEKT" -> "UTC+05"
    ).flatMap { case (k, v) =>
      Try(ZoneId.of(v)).toOption.map { zone =>
        k.toLowerCase(Locale.ENGLISH) -> zone
      }.toMap
    }
  }
}
