addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.typesafe.sbt"    % "sbt-native-packager" % "1.7.6")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.2.1")
