addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.4.5")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager" % "1.9.7")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "1.1.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.2.1")
