addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"      % "sbt-native-packager" % "1.9.9")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "1.2.0")
addSbtPlugin("com.eed3si9n"        % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.2.2")
